version = "1.0"

[generator]
mode = "sample"
count = 1000
speed = 1000
parallel = 1

[output]
# 仅当存在 connect 时，其他 output 字段和旧式 [output.*] 子块将被忽略
connect = "kafka_sink"
name = "generator_output"
# 覆写允许的参数（参考 connectors/sink.d 中对应连接器 allow_override）
# params= { topic = "wp.input.event" ,brokers = "43.138.236.82:30011" }
params= { topic = "wp.input.event" ,brokers = "106.55.164.250:9092" }

# [output]
# # 仅当存在 connect 时，其他 output 字段和旧式 [output.*] 子块将被忽略
# connect = "kafka_sink"
# name = "generator_output"
# # 覆写允许的参数（参考 connectors/sink.d 中对应连接器 allow_override）
# params= { topic = "wp.input.event"  }

[logging]
level = "warn,ctrl=info"
output = "file"
file_path = "./data/logs/"
