# [[sources]]
# enable =  true
# key = "syslog_1"
# connect = "syslog_tcp_src"
# params = { header_mode = "parse", prefer_newline = true , port =1514}


# [[sources]]
# enable = false
# key = "syslog_2"
# connect = "syslog_tcp_src"
# params = { header_mode = "parse", prefer_newline = true , port = 1515}

# [[sources]]
# key = "file_1"
# enable = true
# connect = "file_src"
# tags = ["wpsrc_in_ip : 10.0.0.1"]

[[sources]]
enable =  true
key = "tcp_1"
connect = "tcp_src"
params = { prefer_newline = true , port =19002, instances = 1}