# TCP输入源
[[sources]]
enable =  true
key = "tcp_1"
connect = "tcp_src"
params = { prefer_newline = true , port =19002, instances = 1}

# kafka输入源
[[sources]]
enable = true
key = "kafka_input"
connect = "kafka_src"
#tags = ["type:file", "purpose:benchmark"]
params= { topic = "wp.input.event" ,brokers = "106.55.164.250:9092" }


# [[sources]]
# enable = true
# key = "kafka_output_tap"
# connect = "kafka_src"
# #tags = ["type:file", "purpose:benchmark"]
# params = { topic = "wp.output.event" }